# -*- coding: utf-8 -*-
"""fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnxuxw_ZbdIimcX_6LphqAbWGf7TS3wC
"""

n = int(input("Enter position: "))

a = 0
b = 1

for i in range(n):
    a, b = b, a + b

print(a)

