# -*- coding: utf-8 -*-
"""prompt engineeering 1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnxuxw_ZbdIimcX_6LphqAbWGf7TS3wC
"""

n = 5
fact = 1

while(n > 0):
  fact = fact*n
  n = n-1

print("Factorial of n is ",fact)